/// Flutter icons FreteIcones
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FreteIcones
///      fonts:
///       - asset: fonts/FreteIcones.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FreteIcones {
  FreteIcones._();

  static const _kFontFam = 'FreteIcones';

  static const IconData iconfinder_energy_energy_fuel_fasoline_oil_jerry_cans_3911258 = IconData(0xe800, fontFamily: _kFontFam, );
  static const IconData iconfinder_gas_1055052 = IconData(0xe801, fontFamily: _kFontFam, );
  static const IconData iconfinder_fuel_can_gas_can_gas_container_gasoline_can_jerry_can_4752987 = IconData(0xe802, fontFamily: _kFontFam, );
  static const IconData location = IconData(0xe803, fontFamily: _kFontFam, );
  static const IconData map_marker_alt = IconData(0xf3c5, fontFamily: _kFontFam, );
  static const IconData oil_can = IconData(0xf613, fontFamily: _kFontFam, );
}
