import 'package:rbdevvisitasapp/consts/consts.dart';
import 'package:rbdevvisitasapp/functions/fn_utils.dart';

class VisitanteModel {
  String _PESNOME;
  DateTime _PESDATACADASTRO;
  String _PESCELULAR;
  String _PESINTERNO;
  String _PESVISITANTE;
  String _PESLOGRADOURO;
  String _PESNUMEROLOGRADOURO;
  String _PESCOMPLEMENTODOENDERECO;
  String _PESBAIRRO;
  String _PESCEP;
  int _MUNICIPIOID;
  String _PESCPF;
  int _PESRG;
  String _PESORGAOEMISSORDORG;
  String _PESPAIVIVO;
  String _PESMAEVIVA;
  int _PROFISSAOID;
  String _SEXOID;
  String _PESCADASTROVALIDO;
  int _NACIONALIDADEID;
  int _MUNICIPIONATURALIDADEID;
  int _ESCOLARIDADEID;
  int _RELIGIAOID;
  int _GENEROSEXUALID;
  String _PESBLOQUEADO;
  int _ESTADOCIVILID;
  String _PESRGUF;
  int _MUNICIPIOIDTITULOELEITORAL;
  String _UFCTPSID;
  int _PESCIDADESUS;
  int _CORDAPELEID;
  int _TIPODECABELOID;
  int _TIPODETESTAID;
  int _TIPODEROSTOID;
  int _TIPODEORELHAID;
  int _TIPODESOMBRANCELHAID;
  int _TIPODEBARBAID;
  int _PARTICULARIDADEID;
  int _TIPODEOLHOID;
  int _TIPODENARIZID;
  int _TIPODEBOCAID;
  int _TIPODELABIOID;
  int _TIPODEBIGODEID;
  int _TIPODEPESCOCOID;
  int _ALTURAID;
  int _PESOID;
  int _CAMISAID;
  int _CALCAID;
  int _SAPATOID;
  int _NIVELDECONVIVENCIAID;
  int _RENDAFAMILIARID;
  DateTime _PESDATADENASCIMENTO;
  int _PESSOAID;
  String _PESEMAIL;
  int _UNICODIGO;
  String _VISITANTEGUID;
  String _VISITANTEFOTO;
  bool _VIEW_HASFOTOCHANGED;

  VisitanteModel(
      {String PESNOME,
      DateTime PESDATACADASTRO,
      String PESCELULAR,
      String PESINTERNO,
      String PESVISITANTE,
      String PESLOGRADOURO,
      String PESNUMEROLOGRADOURO,
      String PESCOMPLEMENTODOENDERECO,
      String PESBAIRRO,
      String PESCEP,
      int MUNICIPIOID,
      String PESCPF,
      int PESRG,
      String PESORGAOEMISSORDORG,
      String PESPAIVIVO,
      String PESMAEVIVA,
      int PROFISSAOID,
      String SEXOID,
      String PESCADASTROVALIDO,
      int NACIONALIDADEID,
      int MUNICIPIONATURALIDADEID,
      int ESCOLARIDADEID,
      int RELIGIAOID,
      int GENEROSEXUALID,
      String PESBLOQUEADO,
      int ESTADOCIVILID,
      String PESRGUF,
      int MUNICIPIOIDTITULOELEITORAL,
      String UFCTPSID,
      int PESCIDADESUS,
      int CORDAPELEID,
      int TIPODECABELOID,
      int TIPODETESTAID,
      int TIPODEROSTOID,
      int TIPODEORELHAID,
      int TIPODESOMBRANCELHAID,
      int TIPODEBARBAID,
      int PARTICULARIDADEID,
      int TIPODEOLHOID,
      int TIPODENARIZID,
      int TIPODEBOCAID,
      int TIPODELABIOID,
      int TIPODEBIGODEID,
      int TIPODEPESCOCOID,
      int ALTURAID,
      int PESOID,
      int CAMISAID,
      int CALCAID,
      int SAPATOID,
      int NIVELDECONVIVENCIAID,
      int RENDAFAMILIARID,
      DateTime PESDATADENASCIMENTO,
      int PESSOAID,
      String PESEMAIL,
      int UNICODIGO,
      String VISITANTEGUID,
      String VISITANTEFOTO,
      bool VIEW_HASFOTOCHANGED}) {
    this._PESNOME = PESNOME;
    this._PESDATACADASTRO = PESDATACADASTRO;
    this._PESCELULAR = PESCELULAR;
    this._PESINTERNO = PESINTERNO;
    this._PESVISITANTE = PESVISITANTE;
    this._PESLOGRADOURO = PESLOGRADOURO;
    this._PESNUMEROLOGRADOURO = PESNUMEROLOGRADOURO;
    this._PESCOMPLEMENTODOENDERECO = PESCOMPLEMENTODOENDERECO;
    this._PESBAIRRO = PESBAIRRO;
    this._PESCEP = PESCEP;
    this._MUNICIPIOID = MUNICIPIOID;
    this._PESCPF = PESCPF;
    this._PESRG = PESRG;
    this._PESORGAOEMISSORDORG = PESORGAOEMISSORDORG;
    this._PESPAIVIVO = PESPAIVIVO;
    this._PESMAEVIVA = PESMAEVIVA;
    this._PROFISSAOID = PROFISSAOID;
    this._SEXOID = SEXOID;
    this._PESCADASTROVALIDO = PESCADASTROVALIDO;
    this._NACIONALIDADEID = NACIONALIDADEID;
    this._MUNICIPIONATURALIDADEID = MUNICIPIONATURALIDADEID;
    this._ESCOLARIDADEID = ESCOLARIDADEID;
    this._RELIGIAOID = RELIGIAOID;
    this._GENEROSEXUALID = GENEROSEXUALID;
    this._PESBLOQUEADO = PESBLOQUEADO;
    this._ESTADOCIVILID = ESTADOCIVILID;
    this._PESRGUF = PESRGUF;
    this._MUNICIPIOIDTITULOELEITORAL = MUNICIPIOIDTITULOELEITORAL;
    this._UFCTPSID = UFCTPSID;
    this._PESCIDADESUS = PESCIDADESUS;
    this._CORDAPELEID = CORDAPELEID;
    this._TIPODECABELOID = TIPODECABELOID;
    this._TIPODETESTAID = TIPODETESTAID;
    this._TIPODEROSTOID = TIPODEROSTOID;
    this._TIPODEORELHAID = TIPODEORELHAID;
    this._TIPODESOMBRANCELHAID = TIPODESOMBRANCELHAID;
    this._TIPODEBARBAID = TIPODEBARBAID;
    this._PARTICULARIDADEID = PARTICULARIDADEID;
    this._TIPODEOLHOID = TIPODEOLHOID;
    this._TIPODENARIZID = TIPODENARIZID;
    this._TIPODEBOCAID = TIPODEBOCAID;
    this._TIPODELABIOID = TIPODELABIOID;
    this._TIPODEBIGODEID = TIPODEBIGODEID;
    this._TIPODEPESCOCOID = TIPODEPESCOCOID;
    this._ALTURAID = ALTURAID;
    this._PESOID = PESOID;
    this._CAMISAID = CAMISAID;
    this._CALCAID = CALCAID;
    this._SAPATOID = SAPATOID;
    this._NIVELDECONVIVENCIAID = NIVELDECONVIVENCIAID;
    this._RENDAFAMILIARID = RENDAFAMILIARID;
    this._PESDATADENASCIMENTO = PESDATADENASCIMENTO;
    this._PESSOAID = PESSOAID;
    this._PESEMAIL = PESEMAIL;
    this._UNICODIGO = UNICODIGO;
    this._VISITANTEGUID = VISITANTEGUID;
    this._VISITANTEFOTO = VISITANTEFOTO;
    this._VIEW_HASFOTOCHANGED = VIEW_HASFOTOCHANGED;
  }

  String get PESNOME => _PESNOME.toUpperCase();

  set PESNOME(String PESNOME) => _PESNOME = PESNOME.toUpperCase();

  DateTime get PESDATACADASTRO => _PESDATACADASTRO;

  set PESDATACADASTRO(DateTime PESDATACADASTRO) => _PESDATACADASTRO =
      PESDATACADASTRO != null ? PESDATACADASTRO : DateTime.now();

  String get PESCELULAR => _PESCELULAR;

  set PESCELULAR(String PESCELULAR) => _PESCELULAR = PESCELULAR;

  String get PESINTERNO => _PESINTERNO;

  set PESINTERNO(String PESINTERNO) =>
      _PESINTERNO = PESINTERNO != null ? PESINTERNO : "N";

  String get PESVISITANTE => _PESVISITANTE;

  set PESVISITANTE(String PESVISITANTE) =>
      _PESVISITANTE = PESVISITANTE != null ? PESVISITANTE : "S";

  String get PESLOGRADOURO => _PESLOGRADOURO.toUpperCase();

  set PESLOGRADOURO(String PESLOGRADOURO) =>
      _PESLOGRADOURO = PESLOGRADOURO.toUpperCase();

  String get PESNUMEROLOGRADOURO => _PESNUMEROLOGRADOURO;

  set PESNUMEROLOGRADOURO(String PESNUMEROLOGRADOURO) =>
      _PESNUMEROLOGRADOURO = PESNUMEROLOGRADOURO;

  String get PESCOMPLEMENTODOENDERECO =>
      _PESCOMPLEMENTODOENDERECO.toUpperCase();

  set PESCOMPLEMENTODOENDERECO(String PESCOMPLEMENTODOENDERECO) =>
      _PESCOMPLEMENTODOENDERECO = PESCOMPLEMENTODOENDERECO.toUpperCase();

  String get PESBAIRRO => _PESBAIRRO.toUpperCase();

  set PESBAIRRO(String PESBAIRRO) => _PESBAIRRO = PESBAIRRO.toUpperCase();

  String get PESCEP => _PESCEP;

  set PESCEP(String PESCEP) => _PESCEP = PESCEP;

  int get MUNICIPIOID => _MUNICIPIOID;

  set MUNICIPIOID(int MUNICIPIOID) =>
      _MUNICIPIOID = MUNICIPIOID != null ? MUNICIPIOID : 0;

  String get PESCPF => _PESCPF.replaceAll('.', '').replaceAll('-', '');

  set PESCPF(String PESCPF) =>
      _PESCPF = PESCPF.replaceAll('.', '').replaceAll('-', '');

  int get PESRG => _PESRG;

  set PESRG(int PESRG) => _PESRG = PESRG;

  String get PESORGAOEMISSORDORG => _PESORGAOEMISSORDORG.toUpperCase();

  set PESORGAOEMISSORDORG(String PESORGAOEMISSORDORG) =>
      _PESORGAOEMISSORDORG = PESORGAOEMISSORDORG.toUpperCase();

  String get PESPAIVIVO => _PESPAIVIVO;

  set PESPAIVIVO(String PESPAIVIVO) =>
      _PESPAIVIVO = PESPAIVIVO != null ? PESPAIVIVO : "S";

  String get PESMAEVIVA => _PESMAEVIVA;

  set PESMAEVIVA(String PESMAEVIVA) =>
      _PESMAEVIVA = PESMAEVIVA != null ? PESMAEVIVA : "S";

  int get PROFISSAOID => _PROFISSAOID;

  set PROFISSAOID(int PROFISSAOID) =>
      _PROFISSAOID = PROFISSAOID != null ? PROFISSAOID : 0;

  String get SEXOID => _SEXOID;

  set SEXOID(String SEXOID) => _SEXOID = SEXOID != null ? SEXOID : '0';

  String get PESCADASTROVALIDO => _PESCADASTROVALIDO;

  set PESCADASTROVALIDO(String PESCADASTROVALIDO) =>
      _PESCADASTROVALIDO = PESCADASTROVALIDO != null ? PESCADASTROVALIDO : "N";

  int get NACIONALIDADEID => _NACIONALIDADEID;

  set NACIONALIDADEID(int NACIONALIDADEID) =>
      _NACIONALIDADEID = NACIONALIDADEID != null ? NACIONALIDADEID : 0;

  int get MUNICIPIONATURALIDADEID => _MUNICIPIONATURALIDADEID;

  set MUNICIPIONATURALIDADEID(int MUNICIPIONATURALIDADEID) =>
      _MUNICIPIONATURALIDADEID =
          MUNICIPIONATURALIDADEID != null ? MUNICIPIONATURALIDADEID : 0;

  int get ESCOLARIDADEID => _ESCOLARIDADEID;

  set ESCOLARIDADEID(int ESCOLARIDADEID) =>
      _ESCOLARIDADEID = ESCOLARIDADEID != null ? ESCOLARIDADEID : 0;

  int get RELIGIAOID => _RELIGIAOID;

  set RELIGIAOID(int RELIGIAOID) =>
      _RELIGIAOID = RELIGIAOID != null ? RELIGIAOID : 0;

  int get GENEROSEXUALID => _GENEROSEXUALID;

  set GENEROSEXUALID(int GENEROSEXUALID) =>
      _GENEROSEXUALID = GENEROSEXUALID != null ? GENEROSEXUALID : 0;

  String get PESBLOQUEADO => _PESBLOQUEADO;

  set PESBLOQUEADO(String PESBLOQUEADO) =>
      _PESBLOQUEADO = PESBLOQUEADO != null ? PESBLOQUEADO : "S";

  int get ESTADOCIVILID => _ESTADOCIVILID;

  set ESTADOCIVILID(int ESTADOCIVILID) =>
      _ESTADOCIVILID = ESTADOCIVILID != null ? ESTADOCIVILID : 0;

  String get PESRGUF => _PESRGUF;

  set PESRGUF(String PESRGUF) => _PESRGUF = PESRGUF != null ? PESRGUF : "AA";

  int get MUNICIPIOIDTITULOELEITORAL => _MUNICIPIOIDTITULOELEITORAL;

  set MUNICIPIOIDTITULOELEITORAL(int MUNICIPIOIDTITULOELEITORAL) =>
      _MUNICIPIOIDTITULOELEITORAL =
          MUNICIPIOIDTITULOELEITORAL != null ? MUNICIPIOIDTITULOELEITORAL : 0;

  String get UFCTPSID => _UFCTPSID;

  set UFCTPSID(String UFCTPSID) =>
      _UFCTPSID = UFCTPSID != null ? UFCTPSID : '00';

  int get PESCIDADESUS => _PESCIDADESUS;

  set PESCIDADESUS(int PESCIDADESUS) =>
      _PESCIDADESUS = PESCIDADESUS != null ? PESCIDADESUS : 0;

  int get CORDAPELEID => _CORDAPELEID;

  set CORDAPELEID(int CORDAPELEID) =>
      _CORDAPELEID = CORDAPELEID != null ? CORDAPELEID : 0;

  int get TIPODECABELOID => _TIPODECABELOID;

  set TIPODECABELOID(int TIPODECABELOID) =>
      _TIPODECABELOID = TIPODECABELOID != null ? TIPODECABELOID : 0;

  int get TIPODETESTAID => _TIPODETESTAID;

  set TIPODETESTAID(int TIPODETESTAID) =>
      _TIPODETESTAID = TIPODETESTAID != null ? TIPODETESTAID : 0;

  int get TIPODEROSTOID => _TIPODEROSTOID;

  set TIPODEROSTOID(int TIPODEROSTOID) =>
      _TIPODEROSTOID = TIPODEROSTOID != null ? TIPODEROSTOID : 0;

  int get TIPODEORELHAID => _TIPODEORELHAID;

  set TIPODEORELHAID(int TIPODEORELHAID) =>
      _TIPODEORELHAID = TIPODEORELHAID != null ? TIPODEORELHAID : 0;

  int get TIPODESOMBRANCELHAID => _TIPODESOMBRANCELHAID;

  set TIPODESOMBRANCELHAID(int TIPODESOMBRANCELHAID) => _TIPODESOMBRANCELHAID =
      TIPODESOMBRANCELHAID != null ? TIPODESOMBRANCELHAID : 0;

  int get TIPODEBARBAID => _TIPODEBARBAID;

  set TIPODEBARBAID(int TIPODEBARBAID) =>
      _TIPODEBARBAID = TIPODEBARBAID != null ? TIPODEBARBAID : 0;

  int get PARTICULARIDADEID => _PARTICULARIDADEID;

  set PARTICULARIDADEID(int PARTICULARIDADEID) =>
      _PARTICULARIDADEID = PARTICULARIDADEID != null ? PARTICULARIDADEID : 0;

  int get TIPODEOLHOID => _TIPODEOLHOID;

  set TIPODEOLHOID(int TIPODEOLHOID) =>
      _TIPODEOLHOID = TIPODEOLHOID != null ? TIPODEOLHOID : 0;

  int get TIPODENARIZID => _TIPODENARIZID;

  set TIPODENARIZID(int TIPODENARIZID) =>
      _TIPODENARIZID = TIPODENARIZID != null ? TIPODENARIZID : 0;

  int get TIPODEBOCAID => _TIPODEBOCAID;

  set TIPODEBOCAID(int TIPODEBOCAID) =>
      _TIPODEBOCAID = TIPODEBOCAID != null ? TIPODEBOCAID : 0;

  int get TIPODELABIOID => _TIPODELABIOID;

  set TIPODELABIOID(int TIPODELABIOID) =>
      _TIPODELABIOID = TIPODELABIOID != null ? TIPODELABIOID : 0;

  int get TIPODEBIGODEID => _TIPODEBIGODEID;

  set TIPODEBIGODEID(int TIPODEBIGODEID) =>
      _TIPODEBIGODEID = TIPODEBIGODEID != null ? TIPODEBIGODEID : 0;

  int get TIPODEPESCOCOID => _TIPODEPESCOCOID;

  set TIPODEPESCOCOID(int TIPODEPESCOCOID) =>
      _TIPODEPESCOCOID = TIPODEPESCOCOID != null ? TIPODEPESCOCOID : 0;

  int get ALTURAID => _ALTURAID;

  set ALTURAID(int ALTURAID) => _ALTURAID = ALTURAID != null ? ALTURAID : 0;

  int get PESOID => _PESOID;

  set PESOID(int PESOID) => _PESOID = PESOID != null ? PESOID : 0;

  int get CAMISAID => _CAMISAID;

  set CAMISAID(int CAMISAID) => _CAMISAID = CAMISAID != null ? CAMISAID : 0;

  int get CALCAID => _CALCAID;

  set CALCAID(int CALCAID) => _CALCAID = CALCAID != null ? CALCAID : 0;

  int get SAPATOID => _SAPATOID;

  set SAPATOID(int SAPATOID) => _SAPATOID = SAPATOID != null ? SAPATOID : 0;

  int get NIVELDECONVIVENCIAID => _NIVELDECONVIVENCIAID;

  set NIVELDECONVIVENCIAID(int NIVELDECONVIVENCIAID) => _NIVELDECONVIVENCIAID =
      NIVELDECONVIVENCIAID != null ? NIVELDECONVIVENCIAID : 0;

  int get RENDAFAMILIARID => _RENDAFAMILIARID;

  set RENDAFAMILIARID(int RENDAFAMILIARID) =>
      _RENDAFAMILIARID = RENDAFAMILIARID != null ? RENDAFAMILIARID : 0;

  DateTime get PESDATADENASCIMENTO => _PESDATADENASCIMENTO;

  set PESDATADENASCIMENTO(DateTime PESDATADENASCIMENTO) =>
      _PESDATADENASCIMENTO = PESDATADENASCIMENTO;

  int get PESSOAID => _PESSOAID;

  set PESSOAID(int PESSOAID) => _PESSOAID = PESSOAID;

  String get PESEMAIL => _PESEMAIL;

  set PESEMAIL(String PESEMAIL) => _PESEMAIL = PESEMAIL;

  int get UNICODIGO => _UNICODIGO;

  set UNICODIGO(int UNICODIGO) =>
      _UNICODIGO = UNICODIGO != null ? UNICODIGO : 99;

  String get VISITANTEGUID => _VISITANTEGUID;

  set VISITANTEGUID(String VISITANTEGUID) =>
      _VISITANTEGUID = VISITANTEGUID != null ? VISITANTEGUID : uuid.v4();

  String get VISITANTEFOTO => _VISITANTEFOTO;

  set VISITANTEFOTO(String VISITANTEFOTO) => _VISITANTEFOTO = VISITANTEFOTO;

  bool get VIEW_HASFOTOCHANGED => _VIEW_HASFOTOCHANGED;

  set VIEW_HASFOTOCHANGED(bool VIEW_HASFOTOCHANGED) =>
      _VIEW_HASFOTOCHANGED = VIEW_HASFOTOCHANGED;

  VisitanteModel.fromJson(Map<String, dynamic> json) {
    PESNOME = json['PES_NOME'];
    PESDATACADASTRO = stringToDate(json['PES_DATA_CADASTRO']);
    PESCELULAR = json['PES_CELULAR'];
    PESINTERNO = json['PES_INTERNO'];
    PESVISITANTE = json['PES_VISITANTE'];
    PESLOGRADOURO = json['PES_LOGRADOURO'];
    PESNUMEROLOGRADOURO = json['PES_NUMERO_LOGRADOURO'];
    PESCOMPLEMENTODOENDERECO = json['PES_COMPLEMENTO_DO_ENDERECO'];
    PESBAIRRO = json['PES_BAIRRO'];
    PESCEP = json['PES_CEP'];
    MUNICIPIOID = json['MUNICIPIO_ID'];
    PESCPF = json['PES_CPF'];
    PESRG = toInt(json['PES_RG']);
    PESORGAOEMISSORDORG = json['PES_ORGAO_EMISSOR_DO_RG'];
    PESPAIVIVO = json['PES_PAI_VIVO'];
    PESMAEVIVA = json['PES_MAE_VIVA'];
    PROFISSAOID = json['PROFISSAO_ID'];
    SEXOID = json['SEXO_ID'];
    PESCADASTROVALIDO = json['PES_CADASTRO_VALIDO'];
    NACIONALIDADEID = json['NACIONALIDADE_ID'];
    MUNICIPIONATURALIDADEID = json['MUNICIPIO_NATURALIDADE_ID'];
    ESCOLARIDADEID = json['ESCOLARIDADE_ID'];
    RELIGIAOID = json['RELIGIAO_ID'];
    GENEROSEXUALID = json['GENERO_SEXUAL_ID'];
    PESBLOQUEADO = json['PES_BLOQUEADO'];
    ESTADOCIVILID = json['ESTADO_CIVIL_ID'];
    PESRGUF = json['PES_RG_UF'];
    MUNICIPIOIDTITULOELEITORAL = json['MUNICIPIO_ID_TITULO_ELEITORAL'];
    UFCTPSID = json['UF_CTPS_ID'];
    PESCIDADESUS = json['PES_CIDADE_SUS'];
    CORDAPELEID = json['COR_DA_PELE_ID'];
    TIPODECABELOID = json['TIPO_DE_CABELO_ID'];
    TIPODETESTAID = json['TIPO_DE_TESTA_ID'];
    TIPODEROSTOID = json['TIPO_DE_ROSTO_ID'];
    TIPODEORELHAID = json['TIPO_DE_ORELHA_ID'];
    TIPODESOMBRANCELHAID = json['TIPO_DE_SOMBRANCELHA_ID'];
    TIPODEBARBAID = json['TIPO_DE_BARBA_ID'];
    PARTICULARIDADEID = json['PARTICULARIDADE_ID'];
    TIPODEOLHOID = json['TIPO_DE_OLHO_ID'];
    TIPODENARIZID = json['TIPO_DE_NARIZ_ID'];
    TIPODEBOCAID = json['TIPO_DE_BOCA_ID'];
    TIPODELABIOID = json['TIPO_DE_LABIO_ID'];
    TIPODEBIGODEID = json['TIPO_DE_BIGODE_ID'];
    TIPODEPESCOCOID = json['TIPO_DE_PESCOCO_ID'];
    ALTURAID = json['ALTURA_ID'];
    PESOID = json['PESO_ID'];
    CAMISAID = json['CAMISA_ID'];
    CALCAID = json['CALCA_ID'];
    SAPATOID = json['SAPATO_ID'];
    NIVELDECONVIVENCIAID = json['NIVEL_DE_CONVIVENCIA_ID'];
    RENDAFAMILIARID = json['RENDA_FAMILIAR_ID'];
    PESDATADENASCIMENTO = stringToDate(json['PES_DATA_DE_NASCIMENTO']);
    PESSOAID = json['PESSOA_ID'];
    PESEMAIL = json['PES_EMAIL'];
    UNICODIGO = json['UNI_CODIGO'];
    VISITANTEGUID = json['VISITANTE_GUID'];
    VISITANTEFOTO = json['VISITANTE_FOTO'];
    VIEW_HASFOTOCHANGED = json['VIEW_HASFOTOCHANGED'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['PES_NOME'] = this._PESNOME;
    data['PES_DATA_CADASTRO'] = this._PESDATACADASTRO != null
        ? this._PESDATACADASTRO.toIso8601String()
        : null;
    data['PES_CELULAR'] = this._PESCELULAR;
    data['PES_INTERNO'] = this._PESINTERNO;
    data['PES_VISITANTE'] = this._PESVISITANTE;
    data['PES_LOGRADOURO'] = this._PESLOGRADOURO;
    data['PES_NUMERO_LOGRADOURO'] = this._PESNUMEROLOGRADOURO;
    data['PES_COMPLEMENTO_DO_ENDERECO'] = this._PESCOMPLEMENTODOENDERECO;
    data['PES_BAIRRO'] = this._PESBAIRRO;
    data['PES_CEP'] = this._PESCEP;
    data['MUNICIPIO_ID'] = this._MUNICIPIOID;
    data['PES_CPF'] = this._PESCPF;
    data['PES_RG'] = this._PESRG;
    data['PES_ORGAO_EMISSOR_DO_RG'] = this._PESORGAOEMISSORDORG;
    data['PES_PAI_VIVO'] = this._PESPAIVIVO;
    data['PES_MAE_VIVA'] = this._PESMAEVIVA;
    data['PROFISSAO_ID'] = this._PROFISSAOID;
    data['SEXO_ID'] = this._SEXOID;
    data['PES_CADASTRO_VALIDO'] = this._PESCADASTROVALIDO;
    data['NACIONALIDADE_ID'] = this._NACIONALIDADEID;
    data['MUNICIPIO_NATURALIDADE_ID'] = this._MUNICIPIONATURALIDADEID;
    data['ESCOLARIDADE_ID'] = this._ESCOLARIDADEID;
    data['RELIGIAO_ID'] = this._RELIGIAOID;
    data['GENERO_SEXUAL_ID'] = this._GENEROSEXUALID;
    data['PES_BLOQUEADO'] = this._PESBLOQUEADO;
    data['ESTADO_CIVIL_ID'] = this._ESTADOCIVILID;
    data['PES_RG_UF'] = this._PESRGUF;
    data['MUNICIPIO_ID_TITULO_ELEITORAL'] = this._MUNICIPIOIDTITULOELEITORAL;
    data['UF_CTPS_ID'] = this._UFCTPSID;
    data['PES_CIDADE_SUS'] = this._PESCIDADESUS;
    data['COR_DA_PELE_ID'] = this._CORDAPELEID;
    data['TIPO_DE_CABELO_ID'] = this._TIPODECABELOID;
    data['TIPO_DE_TESTA_ID'] = this._TIPODETESTAID;
    data['TIPO_DE_ROSTO_ID'] = this._TIPODEROSTOID;
    data['TIPO_DE_ORELHA_ID'] = this._TIPODEORELHAID;
    data['TIPO_DE_SOMBRANCELHA_ID'] = this._TIPODESOMBRANCELHAID;
    data['TIPO_DE_BARBA_ID'] = this._TIPODEBARBAID;
    data['PARTICULARIDADE_ID'] = this._PARTICULARIDADEID;
    data['TIPO_DE_OLHO_ID'] = this._TIPODEOLHOID;
    data['TIPO_DE_NARIZ_ID'] = this._TIPODENARIZID;
    data['TIPO_DE_BOCA_ID'] = this._TIPODEBOCAID;
    data['TIPO_DE_LABIO_ID'] = this._TIPODELABIOID;
    data['TIPO_DE_BIGODE_ID'] = this._TIPODEBIGODEID;
    data['TIPO_DE_PESCOCO_ID'] = this._TIPODEPESCOCOID;
    data['ALTURA_ID'] = this._ALTURAID;
    data['PESO_ID'] = this._PESOID;
    data['CAMISA_ID'] = this._CAMISAID;
    data['CALCA_ID'] = this._CALCAID;
    data['SAPATO_ID'] = this._SAPATOID;
    data['NIVEL_DE_CONVIVENCIA_ID'] = this._NIVELDECONVIVENCIAID;
    data['RENDA_FAMILIAR_ID'] = this._RENDAFAMILIARID;
    data['PES_DATA_DE_NASCIMENTO'] = this._PESDATADENASCIMENTO != null
        ? this._PESDATADENASCIMENTO.toIso8601String()
        : null;
    data['PESSOA_ID'] = this._PESSOAID;
    data['PES_EMAIL'] = this._PESEMAIL;
    data['UNI_CODIGO'] = this._UNICODIGO;
    data['VISITANTE_GUID'] = this._VISITANTEGUID;
    data['VISITANTE_FOTO'] = this._VISITANTEFOTO;
    data['VIEW_HASFOTOCHANGED'] = this._VIEW_HASFOTOCHANGED;
    return data;
  }
}
